name: Go
on: [push]
jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/checkout@v1

    - name: test
      run: |
        go run github.com/ysmood/golangci-lint@latest
        go test -coverprofile=coverage.out
        go run github.com/ysmood/got/cmd/check-cov@latest
