name: Go
on: [push]
jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v1

    - name: setup
      run: go get github.com/ysmood/kit/cmd/godev
 
    - name: test
      run: godev -lm 100
