name: Go
on: [push]
jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v1

    - name: setup
      run: curl -L https://git.io/fjaxx | repo=ysmood/kit bin=godev sh
 
    - name: test
      run: godev -l
